{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "k8s-ai-sre.namespace" . }}
  labels:
    {{- include "k8s-ai-sre.labels" . | nindent 4 }}
{{- end }}
