apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deploy
  namespace: ai-sre-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-deploy
  template:
    metadata:
      labels:
        app: bad-deploy
    spec:
      containers:
        - name: app
          image: nginx:does-not-exist
